### PR TITLE
Test with Ruby 2.4, fix warnings

### PR DESCRIPTION
**Pull request by bquorning**
Fixed four types of warnings:

1. warning: constant ::Fixnum is deprecated
2. warning: constant ::Bignum is deprecated
3. warning: ambiguous first argument; put parentheses or a space even after `-' operator
4. warning: loading in progress, circular require considered harmful

### CODE REVIEW

**Comment by grosser** [comment]
hmm I liked the require since it makes every part useable ... how about changing the load order ... require constraint first and then all the constraints ?

**Comment by bquorning** [comment]
When loading a single constraint, is it important to 1) load all the other constraints, or 2) load the base constraint that the specific constraint inherits from?

**Comment by grosser** [comment]
just the base :)

**Comment by bquorning** [comment]
Then I can split the base away from the code that loads all constraints. Problem solved.

**Comment by bquorning** [comment]
Green build! Can I get a final review?

**Pull request merged**
