### PR TITLE
Compatibility with Rails 5.0

### PR DESCRIPTION
**Pull request by pschambacher**
:octopus::computer:

/cc @bquorning @grosser 

### Description
Most of the fight was due to the fact that `ActionController::Parameters` doesn't inherit from `Hash` anymore.

### Steps to merge
* [ ] :+1: from the team

### Risks
* None (behind version guard)

### CODE REVIEW

**Comment by bquorning** [comment]
:+1:

**Comment by grosser** [comment]
:+1:

**Comment by pschambacher** [comment]
@grosser can you please release (and add me on rubygems)?

**Comment by grosser** [comment]
released and added!

On Tue, Feb 2, 2016 at 9:38 AM, Pierre Schambacher <notifications@github.com

**Comment by pschambacher** [comment]
:tophat: thanks

**Pull request merged**
