### PR TITLE
String constraint with valid encoding

### PR DESCRIPTION
**Pull request by bwillis**
I'm curious what you think of this change, we see these encoding issues a lot and thought that this might be a good place to catch them.

### CODE REVIEW

**Comment by grosser** [comment]
hmm that sounds useful ... 
thoughts @staugaard @pschambacher @jespr  ?

**Comment by pschambacher** [comment]
@ciaranarcher @lukkry Useful for us maybe?

**Comment by ciaranarcher** [comment]
I'm a :+1: - can't see the harm in it.

**Comment by jespr** [comment]
Looks good to me as well :+1:

**Comment by grosser** [comment]
2.1.0

**Comment by bwillis** [comment]
Awesome! Thanks for releasing :smile:

**Pull request merged**
