### PR TITLE
Add option to StringConstraint: minimum_length

### PR DESCRIPTION
**Pull request by esjee**
Hello,

It turns out there's a couple of use cases for us where it's useful to require a minimum length. I think this PR does the trick. Let me know what you think.

### CODE REVIEW

**Comment by staugaard** [comment]
:+1:

**Comment by grosser** [comment]
thx, 2.4.0 is out!

**Comment by esjee** [comment]
Great, thanks guys! :)

**Comment by grosser** [comment]
thanks for the PR ;)

**Pull request merged**
