### PR TITLE
add nil constraint

### PR DESCRIPTION
**Pull request by grosser**
need this for https://github.com/zendesk/stronger_parameters/pull/11

@staugaard @Fodoj

### CODE REVIEW

**Comment by kintner** [comment]
:+1:

**Comment by Fodoj** [comment]
Looks fine, but I can't imagine use case for this (except dealing with array constraints). Who would enforce `nil` param? :)

**Comment by grosser** [comment]
It's only useful in combination with other things like `string | nil` /
`integer | nil`

**Comment by staugaard** [comment]
:+1:

**Pull request merged**
